### ISSUE TITLE
ARM64 images

### ISSUE THREAD

**Issue by johnykes** [multiversx/mx-chain-observing-squad#72]
Hello guys :)

Hope you're well!

Just tried to deploy an observing squad on ARM64 and it seems that the images from the docker hub does not support that yet.

Pushing some ARM64 images on the docker hub / creating a snapshotless AWS machine would be great.

See ya & thanks!

**Comment by danidrasovean** [comment]
Hello,

We are currently working on this issue (https://github.com/multiversx/mx-chain-testnet-config/pull/338).
Some more testing of the arm64 docker images is necessary though, which will take more time.

I will inform you once everything is ready and published to DockerHub.

**Comment by danidrasovean** [comment]
Hi @johnykes,

The images required to deploy an observing squad on arm64 architectures are now available on Dockerhub.

**Comment by danidrasovean** [comment]
Hi @johnykes,

The images required to deploy an observing squad on arm64 architectures are now available on Dockerhub.
